### ISSUE TITLE
Installer Stalls

### ISSUE THREAD

**Issue by mrenvoize** [PTFS-Europe/docker-koha-dev#1]
For me running 'docker build -t=”alex/koha-dev:init” .' stalls at the following stage:

Step 5 : RUN git clone https://github.com/Koha-Community/Koha.git
 ---> Running in 24f0b16ae332
Cloning into 'Koha'...

Any thoughts Alex?

**Comment by mrenvoize** [comment]
Hmm, ignore this, it just took 4 goes and 5 hours to do the full clone.. strange.. perhaps some feedback that somthing is happneing would be useful if possible?

**Comment by a-sassmannshausen** [comment]
Agreed — yeah, perhaps at least a warning in the README, but feedback would be ideal...

**Comment by a-sassmannshausen** [comment]
I've left it at the warning in the README.
