### ISSUE TITLE
Missing Perl dependency libdbix-connector-perl

### ISSUE THREAD

**Issue by mjlassila** [PTFS-Europe/docker-koha-dev#4]
Installer stalls because of missing Perl dependency libdbix-connector-perl. Adding this to the Dockerfile, image is built fine.

**Comment by a-sassmannshausen** [comment]
Heya,

Thanks for pointing that out — I've added the instruction not to this container, but to docker-koha-base, as it's probably a requirement for both now (or soon).

Alex
